### ISSUE TITLE
Could not get usedSpace: IO error

### ISSUE THREAD

**Issue by WilhelmGGW** [Storj/storjshare-gui#407] opened 2016-10-15 14:56 UTC
**Versions**

- **GUI Version:** v2.0.10
- **Operating System:** Linux Mint 17

**Expected Behavior**

Run multiple nodes, each with its unique destination folder.

**Actual Behavior**

With multiple nodes set up on computer, the log (upon startup for each node) has a field like this: 

> {error} [Sat Oct 15 2016 08:19:58 GMT-0500 (CDT)] Could not get usedSpace: IO error: lock /media/gary/Seagate Expansion Drive/Storj5/sharddata.kfs/001.s/LOCK: already held by process

The Developer Tools Console also has an entry like this:

> /opt/storjshare/resources/app.asar/node_modules/vue/dist/vue.common.js:1137 [Vue warn]: Invalid setter expression: userdata.tabs[current].lastChange.toLocaleString()

All of the program target folders are unique. And program will usually start and run each individual node normally, if started by itself. However, it will never run more than two nodes at the same time without crashing quickly; and, even with just two nodes running, program crashes frequently. I cannot tic the box to Share previously running drives at launch. I have six nodes on this computer: One folder set on the CPU and five folders on an external HDD.

**Comment by littleskunk** [comment] 2016-10-15 15:40
https://github.com/Storj/storjshare-cli/issues/191

**Comment by WilhelmGGW** [comment] 2016-10-15 16:14
I now see those same messages appear from time to time after startup, as well.

**Comment by aleitner** [comment] 2016-10-20 16:35
Closing this because it's a duplicate of what littleskunk linked to

**Closed by aleitner** 2016-10-20 16:35 UTC
Labels: bug
