### ISSUE TITLE
Windows Firewall Rules Added Name Incorrect

### ISSUE THREAD

**Issue by computeronix** [Storj/storjshare-gui#353] opened 2016-08-20 18:12 UTC
### Versions

- **GUI Version:** v2.0.3
- **Operating System:** Windows 10

### Expected Behavior

```
When adding Windows Firewall rules automatically, the name is added as the description.  The name should be storjshare-gui or Storj or whatever is decided
```

### Actual Behavior

```
The description is the firewall rule name
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Install GUI
2. Start GUI
3. Hit accept for the firewall rules
4. Review Firewall rules in Windows Advanced Security

### Screenshots (Optional)

<img width="490" alt="screen shot 2016-08-20 at 2 10 01 pm" src="https://cloud.githubusercontent.com/assets/19168174/17832986/0eb0e2b6-66e0-11e6-95f0-07ec8d2b10be.png">

**Comment by super3** [comment] 2016-10-10 16:10
@littleskunk Thoughts? Somehow the description got swapped with the title somewhere?

**Comment by littleskunk** [comment] 2016-10-10 16:54
I have to read some manuals. As far as I know we set Name and Description correct. On the first execution Windows will ask for a firewall rule and for some reason add it wrong.

**Comment by littleskunk** [comment] 2016-10-10 22:37
![screenshot](https://cloud.githubusercontent.com/assets/6333390/19253359/e5949d4e-8f4a-11e6-9650-6c59cbabf944.jpg)

**Comment by computeronix** [comment] 2016-10-10 22:45
That's correct but the way the rule is added is incorrect which is very interesting


On Oct 10, 2016, at 6:37 PM, littleskunk <notifications@github.com<mailto:notifications@github.com>> wrote:


[screenshot]<https://cloud.githubusercontent.com/assets/6333390/19253359/e5949d4e-8f4a-11e6-9650-6c59cbabf944.jpg>

-

**Comment by littleskunk** [comment] 2016-10-12 17:17
I checked a few other apps like armory and bitcoin core. It is not a bug it is a feature.  "bitcoin-qt.exe" will be displayed as "Bitcoin Core (GUI node for Bitcoin)". I can understand why microsoft is using the file description.
-> We should change the descript.

I checked the storjshare-gui installer. The descript will not be displayed. 
-> We can write anything in the description. The user will never notice it.

I will change the description into "Storj Share GUI". I will open a pull request and build test binaries. I will have to check Linux and OSX as well but they should not stop us. Worst case we can set different description for each OS.

**Comment by littleskunk** [comment] 2016-10-12 20:40
Fixed with the next release. The fix will only work for the first installation. Once installed windows will keep the firewall rule even if a new version gets installed.

![screenshot](https://cloud.githubusercontent.com/assets/6333390/19326733/03fb5110-90cc-11e6-9b53-c19711134e1b.jpg)

**Comment by super3** [comment] 2016-10-12 22:26
@littleskunk Thanks

**Closed** 2016-10-14 15:36 UTC
Labels: design, needs review
