### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by soeren-b-c** [Storj/storjshare-gui#319] opened 2016-07-29 17:36 UTC
### Versions

Replace the values below with your own:

- **Storj Share:** v1.0.3
- **Core Library:** 2.0.7
- **Operating System:** Ubuntu 16.04

### Expected Behavior

I get the white screen of death quite often. Most of the time there is nothing of interest to find in the logs, but today I got this:

2016/07/28-22:10:30.583651 7fac26914700 Delete type=2 #82600
2016/07/28-22:10:30.587293 7fac26914700 Compacting 1@2 + 12@3 files
2016/07/28-22:10:30.615990 7fac26914700 Generated table #83932: 8 keys, 3822 bytes
1900/01/00-00:00:00.724592 7fac26914700 Generated table #83933: 33 keys, 2105569 bytes
1900/01/00-00:00:00.725247 7fac26914700 compacted to: files[ 0 4 81 616 5182 3608 0 ]
1900/01/00-00:00:00.725411 7fac26914700 Compaction error: IO error: /home/storj2/mount-disks/storj2-sea-418AS/farmer.db/083934.ldb: Too many open files

### Actual Behavior

I expect not to get White Screen of Death :)

**Comment by bookchin** [comment] 2016-08-04 19:43
Duplicate of #317, see the last comment there.

**Closed** 2016-08-04 19:43 UTC
Labels: bug
