### ISSUE TITLE
Bandwidth limiting or scheduling

### ISSUE THREAD

**Issue by jhiswin** [Storj/storjshare-gui#361] opened 2016-08-23 20:59 UTC
### Versions

Replace the values below with your own:

- **GUI Version:** v1.0.3
- **Operating System:** 

### Expected Behavior

Would be helpful to have bandwidth control and scheduling, for connections that cannot afford to be fully saturated or has peak usage times.

**Comment by super3** [comment] 2016-08-24 12:55
Duplicate of https://github.com/Storj/storjshare-gui/issues/281

There are a dozen 3rd party tools that do this already. 
Windows: Net Balancer
Mac: Waterroof or Noobproof
Linux: Wondershaper

**Closed by super3** 2016-08-24 12:55 UTC
