### ISSUE TITLE
Error: Write after end

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/storjshare-gui#547] opened 2017-05-03 01:05 UTC
### Versions

Replace the values below with your own:

- **GUI Version:** v5.0.0
- **Operating System:** windows 10 64bit

### Expected Behavior

Please describe the program's expected behavior.

```
select a node and click `stop` stops the node
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
select a node and click stop it throws a error and restarts
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)

![capture](https://cloud.githubusercontent.com/assets/11735738/25645300/a63696ac-2fa4-11e7-89d5-ba2c8fc947a1.JPG)

**Comment by moto456r** [comment] 2017-05-03 01:07
I experienced this issue when restarting a node. I happened on multiple nodes and also after a clean install of storj GUI.

**Comment by littleskunk** [comment] 2017-05-03 06:40
I am not able to reproduce this issue. I can stop and restart my 2 nodes without any problems. Can you give me some more informations please?

**Comment by MrFancyMonocle** [comment] 2017-05-05 17:42
This is a bit confusing: the attached screenshot shows an error that occurred in a pre-release version of 5.0.0; it should be fixed in the released. Please fill out the steps to reproduce and include how many shares are being run. I haven't been able to reproduce.

**Closed** 2017-05-05 23:42 UTC
Labels: more info needed
