### ISSUE TITLE
Stopping storj doesn't actually stop storj

### ISSUE THREAD

**Issue by utdrmac** [Storj/storjshare-gui#373] opened 2016-09-07 16:16 UTC
### Versions

Replace the values below with your own:

- **Storj Share:** 2.0.6
- **Core Lib:** 3.1.1
- **Protocol:** 0.8.1
- **Operating System:** Ubuntu 14.04

### Expected Behavior

When I click on the green 'Storj Share is Running' button in an attempt to stop everything, I expect everything to stop. IMO, the button should say 'Stop' and the "running" text should be static. It's not quite clear that clicking this green button will stop things. Green doesn't mean stop in any country.

### Actual Behavior

When clicking the above button, it changes back to orange but if you `tail -f` the current log, you can clearly see that traffic is still coming and going. It was necessary to stop the GUI process in order for storj to actually stop.

**Comment by super3** [comment] 2016-09-09 16:20
@utdrmac You are describing two issues here. Not going to address the UX one unless you create another issue for it. For the continuing process please provide the log after you stop. You are sure you don't have any other farmers running at the time?

**Comment by utdrmac** [comment] 2016-09-09 16:25
Nothing else running. Only using the GUI and the features contained therein. I don't have that log anymore. All I can tell you is what is above. I clicked the button to stop the process, button changed, but the logs continued to indicate running behavior. `netstat` still showed a bound/LISTENING socket.

**Comment by super3** [comment] 2016-09-09 16:44
@utdrmac It would be very helpful to us if you reproduced and provided the logs.

**Comment by aleitner** [comment] 2016-10-04 19:49
Can you reproduce this again? I looked through the code and I'm not seeing anything that would cause this

**Comment by utdrmac** [comment] 2016-10-04 20:14
I'm sorry but I haven't been able to reproduce it.

**Comment by aleitner** [comment] 2016-10-05 15:59
I'm closing this until someone else can reproduce it. I'm not able to reproduce it either

**Closed** 2016-10-05 15:59 UTC
Labels: enhancement
