### ISSUE TITLE
Stuck Preparing

### ISSUE THREAD

**Issue by digidan** [Storj/storjshare-gui#454] opened 2016-11-16 21:30 UTC
### Versions

Replace the values below with your own:

- **GUI Version:** v3.0.1
- **Operating System:** Windows 10

### Expected Behavior

Hit start and program goes to preparing which eventually runs or fails in a reasonable amount of time.  

```

```

### Actual Behavior

Hit start, and program goes to preparing, and never errors out of starts, leading to it just hanging in preparing. 

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...Start Storj
2. ...Hit start button
3. ...Instance hangs in preparing state
![screen shot 2016-11-16 at 3 29 10 pm](https://cloud.githubusercontent.com/assets/8356662/20366609/85b4785c-ac11-11e6-95ba-ca01ba78a2c1.png)

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment] 2016-11-17 07:27
Logfile please!

**Comment by digidan** [comment] 2016-11-17 14:38
I'm happy to submit a log, which it actually writes to on OS X, when this occurs on windows 10 it doesn't write to the log file during this process.

**Comment by digidan** [comment] 2016-11-17 14:39
[StorjDrive-0933a1_2016-11-16.txt](https://github.com/Storj/storjshare-gui/files/597623/StorjDrive-0933a1_2016-11-16.txt)
[StorjDrive-f05727_2016-11-16.txt](https://github.com/Storj/storjshare-gui/files/597625/StorjDrive-f05727_2016-11-16.txt)

**Comment by littleskunk** [comment] 2016-11-17 15:06
Anything on the developer console? Menu->View

**Comment by stricq** [comment] 2016-11-22 19:08
I see this issue, too.  Assuming I can get past the Invalid Storage Size error and then the NTP Timeout error.

**Comment by rami-dabain** [comment] 2016-11-23 10:04
Have same issue, tried to allocate only 50GB and left it for 24 hours, nothing in logs, nothing in dev console

**Comment by littleskunk** [comment] 2016-11-23 11:53
Please open cmd / bash terminal and start it from command line. Any output on the command line?

**Comment by rami-dabain** [comment] 2016-11-23 14:13
`{info} [Wed Nov 23 2016 10:26:40 GMT+0100 (CET)] node created with nodeID a382eef2c1f67fed14ef30d00311f682ef3652c7
{info} [Wed Nov 23 2016 10:26:40 GMT+0100 (CET)] clock is synchronized with ntp, delta: 46
{info} [Wed Nov 23 2016 10:26:40 GMT+0100 (CET)] resolving seeds from https://api.storj.io
{info} [Wed Nov 23 2016 10:26:41 GMT+0100 (CET)] attempting to join network via storj://server2dk.ddns.net:4013/b549c9f513cb1fde33adce9573884e107d2b8ea3
{info} [Wed Nov 23 2016 10:26:41 GMT+0100 (CET)] sending FIND_NODE message to {"userAgent":"5.0.1","protocol":"0.10.0","address":"server2dk.ddns.net","port":4013,"nodeID":"b549c9f513cb1fde33adce9573884e107d2b8ea3","lastSeen":1479893201022}
{warn} [Wed Nov 23 2016 10:26:41 GMT+0100 (CET)] missing or empty reply from contact
{warn} [Wed Nov 23 2016 10:27:10 GMT+0100 (CET)] rpc call cb0bd2ede83d72efda44541755160bc7f5712a17 timed out
{warn} [Wed Nov 23 2016 10:27:10 GMT+0100 (CET)] query failed, removing contact for shortlist, reason RPC with ID `cb0bd2ede83d72efda44541755160bc7f5712a17` timed out
{warn} [Wed Nov 23 2016 10:27:10 GMT+0100 (CET)] failed to connect to seed storj://server2dk.ddns.net:4013/b549c9f513cb1fde33adce9573884e107d2b8ea3
{info} [Wed Nov 23 2016 10:27:10 GMT+0100 (CET)] attempting to join network via storj://163.172.80.93:5009/e43225b16b1c65e335b2792d7e470ff6c96528d3
{info} [Wed Nov 23 2016 10:27:10 GMT+0100 (CET)] sending FIND_NODE message to {"userAgent":"5.0.1","protocol":"0.10.0","address":"163.172.80.93","port":5009,"nodeID":"e43225b16b1c65e335b2792d7e470ff6c96528d3","lastSeen":1479893230277}
{warn} [Wed Nov 23 2016 10:27:10 GMT+0100 (CET)] missing or empty reply from contact
{info} [Wed Nov 23 2016 10:27:44 GMT+0100 (CET)] node created with nodeID a382eef2c1f67fed14ef30d00311f682ef3652c7
{info} [Wed Nov 23 2016 10:27:44 GMT+0100 (CET)] clock is synchronized with ntp, delta: 57
{info} [Wed Nov 23 2016 10:27:44 GMT+0100 (CET)] resolving seeds from https://api.storj.io`

**Comment by littleskunk** [comment] 2016-11-23 18:17
@rami-dabain You are running an old version. Other nodes drop your FIND_NODE and will never Response.

**Comment by rami-dabain** [comment] 2016-11-24 10:12
@littleskunk so the version currently on the website is outdated ?

**Comment by littleskunk** [comment] 2016-11-24 11:55
@rami-dabain The version on the website is correct but that doesn't mean you are executing the correct version. See https://github.com/Storj/storjshare-gui/issues/448

Other possible reason for your logfile would be a 3 party firewall blocking outgoing traffic. Only paranoid user like me would install an adition firewall to block outgoing traffic. That is very unlikely.

**Comment by rami-dabain** [comment] 2016-11-24 12:31
No firewall here, I am behind a regular router with all features disabled (throttling, firewall, parent control ...)
This is my first time to install the software (unlike #488)

here is the version i am usung:

Storj Share 3.0.1
Core Library 5.0.1
Protocol 0.10.0

BTW I am using Ubuntu :)

**Comment by littleskunk** [comment] 2016-11-24 17:53
@rami-dabain please join us on https://community.storj.io/ and contact me storjshare channel. You can use my node as seed and I will take a look on my logfile.

**Comment by Th3Van** [comment] 2016-12-04 22:53
Don't know if this problem has been resolve in the upcoming GUI release, but here is what is has been discovering so far..

Restarted the GUI since i was testing a few things regarding the bridges. Unfortunately the GUI somehow got stuck on "preparing...", which has been going on for like 2 hours while writing this.
I'm guessing the GUI might go WSOD later, if I just let it continue running... which I'm going to do, and report back here sometime tomorrow.

Storj Share  3.0.1 (32Bit)
Core Library 5.0.1
Protocol 0.10.0
OS : Windows Server 2012 R2 - 64Bit

*Screenshot:*
![storjshare-gui_issue01_001](https://cloud.githubusercontent.com/assets/18688983/20869745/8b0af7d8-ba79-11e6-9513-c93aff62e769.png)

*Log file:*
[Storjshare-GUI_issue01_001.log.txt](https://github.com/Storj/storjshare-gui/files/629884/Storjshare-GUI_issue01_001.log.txt)

Looks like the Tunnel never came up/established due to a request fail from https://api.stor.ip/contacts, and it tries to join a ton of storj nodes, but without success. That's until our old friend "[object Object]" suddenly appears and everything goes totally haywire from there... (@Sun Dec 04 2016 21:48:38)

//TheVan

**Comment by Th3Van** [comment] 2016-12-05 14:35
15 hours later - still "preparing..." and log file are still looping with "removing contact" trying to remove the same node over and over, (but no WSOD.. yet)

```
{debug} [Mon Dec 05 2016 15:19:30 GMT+0100 (Romance Standard Time)] checking pending rpc callbacks for expirations
{warn} [Mon Dec 05 2016 15:19:30 GMT+0100 (Romance Standard Time)] rpc call 43c6aca13e185141f1109bf332ed325448019af0 timed out
{debug} [Mon Dec 05 2016 15:19:30 GMT+0100 (Romance Standard Time)] removing contact {"userAgent":"5.0.1","protocol":"0.10.0","address":"5.37.202.233","port":9954,"nodeID":"01d6356ceb20a31aa0c1c2dcf46e713ec991d251","lastSeen":1480884488423}
{warn} [Mon Dec 05 2016 15:19:30 GMT+0100 (Romance Standard Time)] query failed, removing contact for shortlist, reason RPC with ID `43c6aca13e185141f1109bf332ed325448019af0` timed out
{debug} [Mon Dec 05 2016 15:19:30 GMT+0100 (Romance Standard Time)] removing contact {"userAgent":"5.0.1","protocol":"0.10.0","address":"5.37.202.233","port":9954,"nodeID":"01d6356ceb20a31aa0c1c2dcf46e713ec991d251","lastSeen":1480884488423}
{debug} [Mon Dec 05 2016 15:19:45 GMT+0100 (Romance Standard Time)] checking pending rpc callbacks for expirations
{warn} [Mon Dec 05 2016 15:19:45 GMT+0100 (Romance Standard Time)] rpc call 43c6aca13e185141f1109bf332ed325448019af0 timed out
{debug} [Mon Dec 05 2016 15:19:45 GMT+0100 (Romance Standard Time)] removing contact {"userAgent":"5.0.1","protocol":"0.10.0","address":"5.37.202.233","port":9954,"nodeID":"01d6356ceb20a31aa0c1c2dcf46e713ec991d251","lastSeen":1480884488423}
{warn} [Mon Dec 05 2016 15:19:45 GMT+0100 (Romance Standard Time)] query failed, removing contact for shortlist, reason RPC with ID `43c6aca13e185141f1109bf332ed325448019af0` timed out
{debug} [Mon Dec 05 2016 15:19:45 GMT+0100 (Romance Standard Time)] removing contact {"userAgent":"5.0.1","protocol":"0.10.0","address":"5.37.202.233","port":9954,"nodeID":"01d6356ceb20a31aa0c1c2dcf46e713ec991d251","lastSeen":1480884488423}
{debug} [Mon Dec 05 2016 15:19:46 GMT+0100 (Romance Standard Time)] cleaning bad contacts from routing table
{debug} [Mon Dec 05 2016 15:19:46 GMT+0100 (Romance Standard Time)] dropping 0 bad contacts from router
{debug} [Mon Dec 05 2016 15:20:00 GMT+0100 (Romance Standard Time)] checking pending rpc callbacks for expirations
{warn} [Mon Dec 05 2016 15:20:00 GMT+0100 (Romance Standard Time)] rpc call 43c6aca13e185141f1109bf332ed325448019af0 timed out
{debug} [Mon Dec 05 2016 15:20:00 GMT+0100 (Romance Standard Time)] removing contact {"userAgent":"5.0.1","protocol":"0.10.0","address":"5.37.202.233","port":9954,"nodeID":"01d6356ceb20a31aa0c1c2dcf46e713ec991d251","lastSeen":1480884488423}
{warn} [Mon Dec 05 2016 15:20:00 GMT+0100 (Romance Standard Time)] query failed, removing contact for shortlist, reason RPC with ID `43c6aca13e185141f1109bf332ed325448019af0` timed out
{debug} [Mon Dec 05 2016 15:20:00 GMT+0100 (Romance Standard Time)] removing contact {"userAgent":"5.0.1","protocol":"0.10.0","address":"5.37.202.233","port":9954,"nodeID":"01d6356ceb20a31aa0c1c2dcf46e713ec991d251","lastSeen":1480884488423}
{debug} [Mon Dec 05 2016 15:20:08 GMT+0100 (Romance Standard Time)] cleaning bad contacts from routing table
{debug} [Mon Dec 05 2016 15:20:08 GMT+0100 (Romance Standard Time)] dropping 0 bad contacts from router
{debug} [Mon Dec 05 2016 15:20:15 GMT+0100 (Romance Standard Time)] checking pending rpc callbacks for expirations
{warn} [Mon Dec 05 2016 15:20:15 GMT+0100 (Romance Standard Time)] rpc call 43c6aca13e185141f1109bf332ed325448019af0 timed out
{debug} [Mon Dec 05 2016 15:20:15 GMT+0100 (Romance Standard Time)] removing contact {"userAgent":"5.0.1","protocol":"0.10.0","address":"5.37.202.233","port":9954,"nodeID":"01d6356ceb20a31aa0c1c2dcf46e713ec991d251","lastSeen":1480884488423}
{warn} [Mon Dec 05 2016 15:20:15 GMT+0100 (Romance Standard Time)] query failed, removing contact for shortlist, reason RPC with ID `43c6aca13e185141f1109bf332ed325448019af0` timed out
{debug} [Mon Dec 05 2016 15:20:15 GMT+0100 (Romance Standard Time)] removing contact {"userAgent":"5.0.1","protocol":"0.10.0","address":"5.37.202.233","port":9954,"nodeID":"01d6356ceb20a31aa0c1c2dcf46e713ec991d251","lastSeen":1480884488423}
{debug} [Mon Dec 05 2016 15:20:30 GMT+0100 (Romance Standard Time)] checking pending rpc callbacks for expirations
{warn} [Mon Dec 05 2016 15:20:30 GMT+0100 (Romance Standard Time)] rpc call 43c6aca13e185141f1109bf332ed325448019af0 timed out
```
//Th3Van

**Comment by littleskunk** [comment] 2016-12-05 15:24
@Th3Van Duplicate: https://github.com/Storj/storjshare-cli/issues/226
```
{info} [Sun Dec 04 2016 21:48:38 GMT+0100 (Romance Standard Time)] attempting to join network via storj://[object Object]:4001/9ad7b50716c92d531ac9f43d97bb25459846a187
```

**Comment by Th3Van** [comment] 2016-12-06 01:27
Hey @littleskunk 

Thanks, but that is another issue, that just interferes with this, and therefor secondary ;)
The primary issue (as i understand it) are tunnel not being established, even if the GUI restarts itself after failing getting seeds from api.storj.io.

Expected behavior (using tunnel) : 
```
{warn}  you are not publicly reachable, trying traversal strategies...
{warn}  could not connect to NAT device via UPnP: 25224
{info}  node created with nodeID 7502928e34522b21ff74370e0d8d01db6afaa9ee
{info}  clock is synchronized with ntp, delta: -136
{debug} Request: {"baseUrl":"https://api.storj.io","uri":"/contacts","method":"GET","timeout":20000,"qs":{"__nonce":"8f70e40c-b971-4b0e-9f06-439d34b6c658"},"json":true}
{debug} Body: [{"lastSeen":"2016-12-05T23:33:29.270Z","port":6977,"address":"47.18.37.25","userAgent":"5.0.1","protocol":"0.10.0","nodeID":"a0f156ab90b4cb316e370fa9b50fd3e0961ae81d"},..........]

{info}  requesting probe from nearest neighbor
{info}  sending PROBE message to {"userAgent":"5.0.1","protocol":"0.10.0","address":"47.18.37.25","port":6977,"nodeID":"a0f156ab90b4cb316e370fa9b50fd3e0961ae81d","lastSeen":1480980809547}
{info}  received valid message from {"userAgent":"5.0.1","protocol":"0.10.0","address":"47.18.37.25","port":6977,"nodeID":"a0f156ab90b4cb316e370fa9b50fd3e0961ae81d","lastSeen":1480980809818}

{info}  requesting tunnelers from neighbor
{info}  sending FIND_TUNNEL message to {"userAgent":"5.0.1","protocol":"0.10.0","address":"47.18.37.25","port":6977,"nodeID":"a0f156ab90b4cb316e370fa9b50fd3e0961ae81d","lastSeen":1480980809825}
{info}  received valid message from {"userAgent":"5.0.1","protocol":"0.10.0","address":"47.18.37.25","port":6977,"nodeID":"a0f156ab90b4cb316e370fa9b50fd3e0961ae81d","lastSeen":1480980810106}

{info}  sending OPEN_TUNNEL message to {"userAgent":"5.1.0","protocol":"0.10.0","address":"STORJ-CLUS-066.storj.space","port":4000,"nodeID":"b21ee44ff4aabceb8411b7fe4d3243003a380a1c","lastSeen":1480980810417}
{info}  received valid message from {"userAgent":"5.1.0","protocol":"0.10.0","address":"STORJ-CLUS-066.storj.space","port":4000,"nodeID":"b21ee44ff4aabceb8411b7fe4d3243003a380a1c","lastSeen":1480980810839}

{info}  opening tunnel client to ws://STORJ-CLUS-066.storj.space:4001/tun?token=b82ba91c4a9ba8017cc2de44428834942c2017683b723f17f7330917b9a365fa
{info}  tunnel successfully established: {"address":"STORJ-CLUS-066.storj.space","port":4020}
{info}  testing newly established tunnel: {"address":"STORJ-CLUS-066.storj.space","port":4020}

{info}  resolving seeds from https://api.storj.io
{debug} Request: {"baseUrl":"https://api.storj.io","uri":"/contacts","method":"GET","timeout":20000,"qs":{"connected":true,"__nonce":"440df059-0810-435e-bb7e-be709e39f277"},"json":true}
{debug} Body: [{"lastSeen":"2016-12-05T23:33:31.423Z","port":6025,"address":"163.172.80.93","userAgent":"5.1.2","protocol":"0.10.0","nodeID":"bc803a0154b6be804d746c3c69b653a0f11346f6"},...........]

{info}  attempting to join network via storj://veeit30163.dyndns.org:7050/6f0fd0c7df8134d8a6434eb9a1d083e1c6f58169
{debug} entering overlay network via {"userAgent":"5.0.1","protocol":"0.10.0","address":"veeit30163.dyndns.org","port":7050,"nodeID":"6f0fd0c7df8134d8a6434eb9a1d083e1c6f58169","lastSeen":1480980811629}
{info}  connected to the storj network via storj://veeit30163.dyndns.org:7050/6f0fd0c7df8134d8a6434eb9a1d083e1c6f58169

{info}  subscribing to topic "0f01020202"
{info}  subscribing to topic "0f02020202"
{info}  subscribing to topic "0f03020202"

GUI "Preparing..." --> "Running"
```

What actual happens (tunnel are not established, despite the farmer restarts itself twice = no access to the outside world and attempts to join network fails + GUI hangs on "Preparing...")
```
{warn}  you are not publicly reachable, trying traversal strategies...
{warn}  could not connect to NAT device via UPnP: 64201
{info}  node created with nodeID 7502928e34522b21ff74370e0d8d01db6afaa9ee
{info}  clock is synchronized with ntp, delta: -198
{debug} Request: {"baseUrl":"https://api.storj.io","uri":"/contacts","method":"GET","timeout":20000,"qs":{"__nonce":"5e94f75b-2092-491c-9a8a-4668ea58ad87"},"json":true}
{debug} Body: undefined
{error} Failed to get seeds for probe
{warn}  An error occurred. Restarting farmer [6c95b9]...
{warn}  you are not publicly reachable, trying traversal strategies...
{warn}  could not connect to NAT device via UPnP: 27502
{info}  node created with nodeID 7502928e34522b21ff74370e0d8d01db6afaa9ee
{info}  clock is synchronized with ntp, delta: -199
{debug} Request: {"baseUrl":"https://api.storj.io","uri":"/contacts","method":"GET","timeout":20000,"qs":{"__nonce":"2b862646-281f-49ee-82d3-d27dfad00baf"},"json":true}
{debug} Body: undefined
{error} Failed to get seeds for probe
{warn}  An error occurred. Restarting farmer [6c95b9]...
{warn}  you are not publicly reachable, trying traversal strategies...
{warn}  could not connect to NAT device via UPnP: 56100
{info}  node created with nodeID 7502928e34522b21ff74370e0d8d01db6afaa9ee
{info}  clock is synchronized with ntp, delta: -198
{debug} Request: {"baseUrl":"https://api.storj.io","uri":"/contacts","method":"GET","timeout":20000,"qs":{"__nonce":"e6a1046d-4829-4db0-b2e6-f60cbe3aad6c"},"json":true}
{debug} Body: [{"lastSeen":"2016-12-05T15:20:54.902Z","port":55924,"address":"178.32.218.79","userAgent":"5.0.1","protocol":"0.10.0","nodeID":"fabbfa3443b16684401e972e68a7cc560748d12c"},.........]

{info}  requesting probe from nearest neighbor
{info}  sending PROBE message to {"userAgent":"5.0.1","protocol":"0.10.0","address":"178.32.218.79","port":55924,"nodeID":"fabbfa3443b16684401e972e68a7cc560748d12c","lastSeen":1480951255186}
{warn}  missing or empty reply from contact
{debug} removing contact {"userAgent":"5.0.1","protocol":"0.10.0","address":"178.32.218.79","port":55924,"nodeID":"fabbfa3443b16684401e972e68a7cc560748d12c","lastSeen":1480951255186}

{info}  requesting tunnelers from neighbor
{info}  sending FIND_TUNNEL message to {"userAgent":"5.0.1","protocol":"0.10.0","address":"178.32.218.79","port":55924,"nodeID":"fabbfa3443b16684401e972e68a7cc560748d12c","lastSeen":1480951282957}
{warn}  missing or empty reply from contact
{debug} removing contact {"userAgent":"5.0.1","protocol":"0.10.0","address":"178.32.218.79","port":55924,"nodeID":"fabbfa3443b16684401e972e68a7cc560748d12c","lastSeen":1480951282957}

{info}  requesting tunnelers from neighbor
{info}  sending FIND_TUNNEL message to {"userAgent":"5.1.2","protocol":"0.10.0","address":"49.142.68.172","port":14912,"nodeID":"c442a357a7610731461869e280097fed5bd6a522","lastSeen":1480951312961}
{info}  received valid message from {"userAgent":"5.1.2","protocol":"0.10.0","address":"49.142.68.172","port":14912,"nodeID":"c442a357a7610731461869e280097fed5bd6a522","lastSeen":1480951314337}

--- repeating for like 10 min. :
{debug} cleaning bad contacts from routing table
{debug} dropping 0 bad contacts from router
{debug} checking pending rpc callbacks for expirations
---

{info}  resolving seeds from https://api.storj.io
{debug} Request: {"baseUrl":"https://api.storj.io","uri":"/contacts","method":"GET","timeout":20000,"qs":{"connected":true,"__nonce":"2f47baa5-d20d-4297-bf53-a8b4a1ea9bca"},"json":true}
{debug} Body: [{"lastSeen":"2016-12-05T15:31:54.551Z","port":4000,"address":"STORJ-CLUS-151.storj.space","userAgent":"5.1.2","protocol":"0.10.0","nodeID":"44b5b474cc4c2a2aacfe5e092de1a8a17e721a83"},....some 30 seeds......]

{info}  attempting to join network via storj://178.32.218.79:55924/fabbfa3443b16684401e972e68a7cc560748d12c
{debug} entering overlay network via {"userAgent":"5.0.1","protocol":"0.10.0","address":"178.32.218.79","port":55924,"nodeID":"fabbfa3443b16684401e972e68a7cc560748d12c","lastSeen":1480951914846}
{warn}  failed to connect to seed storj://178.32.218.79:55924/fabbfa3443b16684401e972e68a7cc560748d12c

{info}  attempting to join network via storj://n.storj.eu:4001/8a1d37d4006957a90c47a10c64b9b8e381e08291
{debug} entering overlay network via {"userAgent":"5.0.1","protocol":"0.10.0","address":"n.storj.eu","port":4001,"nodeID":"8a1d37d4006957a90c47a10c64b9b8e381e08291","lastSeen":1480951943194}
{warn}  failed to connect to seed storj://n.storj.eu:4001/8a1d37d4006957a90c47a10c64b9b8e381e08291

{info}  attempting to join network via storj://storj.lksmith.net:46012/7e4af4d7943277fd1387a9250bcc28a95537707a
{debug} entering overlay network via {"userAgent":"5.0.1","protocol":"0.10.0","address":"storj.lksmith.net","port":46012,"nodeID":"7e4af4d7943277fd1387a9250bcc28a95537707a","lastSeen":1480951973202}
{warn}  failed to connect to seed storj://storj.lksmith.net:46012/7e4af4d7943277fd1387a9250bcc28a95537707a

{info}  attempting to join network via storj://91.244.113.103:2721/575991be00c7dca49dc4057911f2d3c5fb83bd56
{debug} entering overlay network via {"userAgent":"5.0.1","protocol":"0.10.0","address":"91.244.113.103","port":2721,"nodeID":"575991be00c7dca49dc4057911f2d3c5fb83bd56","lastSeen":1480952003215}
{warn}  failed to connect to seed storj://91.244.113.103:2721/575991be00c7dca49dc4057911f2d3c5fb83bd56

etc...
```
This goes on until all 30 seeds had been attempted for joining the network and fails.
After that it's just checking for pending RPC's/cleaning bad contacts, until manually restarted.
```
{warn}  missing or empty reply from contact
{debug} cleaning bad contacts from routing table
{debug} dropping 0 bad contacts from router
{debug} checking pending rpc callbacks for expirations
{debug} checking pending rpc callbacks for expirations
{warn}  missing or empty reply from contact
{debug} cleaning bad contacts from routing table
{debug} dropping 0 bad contacts from router
```
*Log File:*
[Storjshare-GUI_issue01_002.log.txt](https://github.com/Storj/storjshare-gui/files/632671/Storjshare-GUI_issue01_002.log.txt)

//Th3Van

**Comment by axiomfinity** [comment] 2016-12-06 03:07
Try update the system clock with pool.ntp.org various times throughout the day ?

**Comment by Th3Van** [comment] 2016-12-06 03:19
NTP pulling every 15 min...
```
C:\>w32tm /monitor /computers:0.dk.pool.ntp.org,1.dk.pool.ntp.org,2.dk.pool.ntp.org,3.dk.pool.ntp.org
0.dk.pool.ntp.org[5.186.54.201:123]:
    ICMP: 5ms delay
    NTP: -0.0822311s offset from local clock
        RefID: ntp1.sptime.se [193.11.166.2]
        Stratum: 2
1.dk.pool.ntp.org[192.36.143.130:123]:
    ICMP: 2ms delay
    NTP: -0.0801483s offset from local clock
        RefID: 'PPS [0x00535050]
        Stratum: 1
2.dk.pool.ntp.org[213.5.39.34:123]:
    ICMP: 4ms delay
    NTP: -0.0804585s offset from local clock
        RefID: sth1.ntp.se [194.58.202.20]
        Stratum: 2
3.dk.pool.ntp.org[92.246.24.228:123]:
    ICMP: 5ms delay
    NTP: -0.0798583s offset from local clock
        RefID: 'kPPS' [0x5350506B]
        Stratum: 1
```

**Comment by littleskunk** [comment] 2016-12-06 07:17
@Th3Van The tunnel problem should be solved with the new core release: https://github.com/Storj/core/issues/539

I can send you the new GUI. Would you like to try it?

**Comment by littleskunk** [comment] 2016-12-09 19:04
New GUI release published. If you get the problem again please open a new issue. Don't forget to add your logfiles ;)

**Closed by littleskunk** 2016-12-09 19:04 UTC
Labels: more info needed
