### ISSUE TITLE
Threats - infections

### ISSUE THREAD

**Issue by excrucio** [storj/storjshare-gui#754] opened 2018-02-06 16:52 UTC
### Versions

GUI 7.3.2
Daemon 5.3.0
Core 8.6.0
Protocol 1.2.0

### OS
win10 64 bit

Getting ***threats*** from today such as:
kap.tcp4.me
mokijoco.ntdll.top
xabapesekad.tcp4.me
and many more 
**tcp4.me** and **.top** urls

![threats](https://user-images.githubusercontent.com/5563016/35872166-6b128c90-0b66-11e8-91f7-15e661ae5501.PNG)

**Comment by excrucio** [comment] 2018-02-10 17:43
**vejoquaxati.forumz.info reporting infected last 2 days...**

**Comment by stefanbenten** [comment] 2018-02-21 11:44
@excrucio This isnt an issue of StorjShare or Storj Labs. The issue is that users create nodes on these IP´s / domains, that a are known for spam or similar. We cannot prevent this creation.
Further your node behaviour shouldnt be affected by this.

**Comment by b-f-** [comment] 2018-03-16 08:51
@stefanbenten Is there a way to edit a whitelist/blacklist of nodes? I would rather see that there are 0 incoming/outgoing connections from suspicious nodes whatsoever.

**Comment by RichardLitt** [comment] 2018-10-30 12:38
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!

**Closed by RichardLitt** 2018-10-30 12:38 UTC
