### ISSUE TITLE
GUI v5.0.0 Ethereum Addresses

### ISSUE THREAD

**Issue by aleitner** [Storj/storjshare-gui#543] opened 2017-05-01 16:10 UTC
Because we're now in May, and we intend to have this new ERC20 thing rolled out, we need to figure out how to transition GUI users from an old counterparty address to an ethereum address.

<3 James

**Comment by JukeboxRhino** [comment] 2017-06-16 20:16
This is a duplicate of #614 (I know this came first but #614 has more specifics)

**Closed** 2017-06-25 00:38 UTC
Labels: chore
