### ISSUE TITLE
The StorjShare GUI stuck on "Checking"

### ISSUE THREAD

**Issue by AlexeyALeonov** [storj/storjshare-gui#764] opened 2018-03-25 12:09 UTC
### Versions

Replace the values below with your own:

- **GUI Version:** v7.3.4
- **Operating System:** Ubuntu 17.10

### Expected Behavior

Please describe the program's expected behavior.

```
I want to add my first drive. I placed the right payout address, selected a folder on the drive and specified amount of allocated space.
On the step when I should specify the port (Step 4), I clicked "Random" and clicked the "Check".
The program started to work.
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
When I clicked the "Next" button in step 4, it switched to "Checking ..." and got stuck here.
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Fresh Ubuntu 17.10.1
2. Install the latest .deb package for 64 bit systems
3. Install the missed dependencies (take a look at the #731 )
4. Start the StorjShare GUI
5. Click the **Start Setup**
6. Place your payout address, click the **Next**
7. Select the storage location on Step 2, click the **Select location**
8. Specify the size of the allocation (*for example - 2048 MB*) on Step 3, click the **Next**
9. Click the **Random** on the Step 4 and click the **Next**
The StorjShare GUI is stuck on the "Checking..."

### Screenshots (Optional)
![default](https://user-images.githubusercontent.com/26858949/37874848-9d58243c-303f-11e8-9016-de96344dfe88.png)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by AlexeyALeonov** [comment] 2018-03-25 12:20
Even if I did port forwarding before the Wizard and select the **reachable** checkbox this doesn't help either.

**Comment by AlexeyALeonov** [comment] 2018-03-25 12:47
The workaround: click the **I'm an experienced user, skip setup** on the first screen, then **+ Add drive**, follow the Wizard and you will be able to finish setup.

**Comment by littleskunk** [comment] 2018-03-27 20:22
Confirmed. For some reason the callback is never called: https://github.com/Storj/storjshare-daemon/blob/c8b616f9339f617eb27f8affbc555796a698a2c0/lib/utils.js#L197

**Comment by therealklanni** [comment] 2018-04-23 17:15
Same issue here. Thanks for the workaround, @AlexeyALeonov ! Hopefully this is fixed soon so less experienced users are able to use the service.

**Comment by Storj39419** [comment] 2018-04-28 17:06
Same issue on Windows as well, I used old version to create nodes, then updated Storj Share.

**Comment by FlatEarthDave** [comment] 2018-05-01 08:33
It was a problem in Windows for me, as well. Thank you for the workaround. I Can't believe this was posted over a month ago, and it's still not fixed.

**Comment by littleskunk** [comment] 2018-05-01 12:38
@FlatEarthDave I am sorry. I am sure I am able to fix this issue but so far I had no time. This issue has a workaround and for that reason can't be top priority.

Feel free to work on a fix. I have the feeling it is a problem with nodejs. An update to the latest nodejs version might fix it.

**Comment by sami8086** [comment] 2018-05-03 14:39
same issue here please give solution of this problem

**Comment by tempestb** [comment] 2018-05-03 14:55
As listed above from Alexey...

"The workaround: click the I'm an experienced user, skip setup on the first screen, then + Add drive, follow the Wizard and you will be able to finish setup."

**Comment by sami8086** [comment] 2018-05-03 15:02
Thanks Working :)

**Comment by strongfellow** [comment] 2018-05-14 20:27
The workaround works but the issue is still there

**Comment by AlexeyALeonov** [comment] 2018-05-14 20:28
Yes, it's still have an open state

**Comment by Hawkcubed** [comment] 2018-05-24 14:06
Thanks for the work around ε-(´・｀) ﾌ

**Comment by payrollDevops** [comment] 2018-06-19 12:56
Hello,  i seem to have fixed the issue.  If you`re stuck on checking in the Gui but are sertain the connection could be made your AV is probably interfering.  please allow the following url. and whiltelist your container as well. Your dayly AV doenst like the encryption behaviour going on inside the container
URL:   http://colourwp.iask.in to whitelist.

Also to get your GUI trough click in the above menu, click Help and then about,  somehow this helps. and i got an all clear and i am up and running now.

Hope this helps someone

**Comment by AlexeyALeonov** [comment] 2018-06-19 17:06
It's reproduced on Linux, there is no AV.

**Comment by RichardLitt** [comment] 2018-10-30 12:38
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!

**Closed by RichardLitt** 2018-10-30 12:38 UTC
