### ISSUE TITLE
GUI 0.8.2 issue

### ISSUE THREAD

**Issue by wyh136** [Storj/storjshare-gui#238] opened 2016-06-11 14:57 UTC
![pasted image at 2016_06_11 09_14 pm](https://cloud.githubusercontent.com/assets/12386613/15985656/e40a0a9a-3027-11e6-9e16-262bec628b7e.png)

**Comment by littleskunk** [comment] 2016-06-12 00:48
I was not able to reproduce it. I used different linux distribution for tests. However on windows the reason was fd-diskspace. I implemented the same fix for linux and I hope it will fix the issue.

https://github.com/SuperPaintman/fd-diskspace/pull/1

Fixed with the next storjshare-gui version.

**Closed by littleskunk** 2016-06-12 00:48 UTC
Labels: in progress

**Comment by littleskunk** [comment] 2016-06-14 10:48
Latest storjshare-gui.amd64.deb has the fix now. Please try again.
