### ISSUE TITLE
Ease of Use Improvement/Suggestion.

### ISSUE THREAD

**Issue by tempestb** [storj/storjshare-gui#513] opened 2017-03-30 18:07 UTC
Background:  Currently, when Storjshare is running, there can be issues that prevent it from running properly.  Many of these issues are mitigated by configuration changes that the user needs to perform.  Other issues occur due to errors that take place.  Perhaps a drive error, or no communication for an extended period.

Support (Heunland, Meije, LittleSkunk) are often asked repetitious questions about Storjshare status.  Such as...

"Why do I have a bunch of contracts but no data?"
"Why haven't I received any data in a while?"
"How do I know if my node is running correctly?"

In most cases, the support person has to ask the user to post their log to the Rocket Chat channel #storjshare.  The Support person has to then look through the log for tell-tale signs of either the node working properly, or throwing some kind of error.

Often, two of the most common errors are that their clock isn't correct and that their ports aren't open.   Both of these are open issues (As of this writing) to be addressed in a future update.  However, even with these fixes, the above illustrates that the end user has no idea what the "status" of their Storjshare is without performing "research" on the log.   This is cumbersome and not ideal for the less technically inclined user.

Suggestion:  I propose an icon on the GUI as well as a message in the "storjshare status" in the daemon, which indicates the current status of the storjshare utility.  I view it as a stop-light, but the aesthetic is of no importance.

Green - Your Storjshare is running properly, communicating, and open for business.
Yellow - Everything is working, but you are currently tunneling.
Red - There is an error, service may be compromised.  Check the log.

The error messages would take precedence over the other colors.  And could be reset to Green/Yellow based on a button to clear the error alert, or restarting and everything checking out ok.  (Could also be a menu option.)  

While catching every error is impossible.  Many errors are already sent to the log.  That same error trap routine could also call a method that changes the status indicator, based on the severity of the error message.  (Assuming some messages are just informational and don't indicate a problem, they would not change the status of the indicator.  Where as ones that hamper Storjshare from working correctly, would throw an error alert.)

In this way, Storjshare operators could view their status simply and efficiently.  And the Storj support team could more easily mitigate support questions about the status if they can just ask the end user, 

"Is your light green?  If so, you're all set."   
...or perhaps...  
"It is yellow?  Ok, your node is unreachable, you can continue to tunnel (Pros/Cons) or port forward" etc. ...where by...
"You say your alert light is Red?  Please post your log and we'll have a look."

Not only just informational, however, is that it is a reassurance to the end user that everything is working properly.  Confidence in the application performing properly will mean that users will be assured that the results they are seeing is a measure of the overall network use, and not because of some unknown error logged inside a big text file.

Meije made note that there could also be an animated icon of a sort, to indicate that Storjshare is not locked up and is still functioning.  Perhaps a meter that shows the number of contracts received in the past 24 hours.  Or the number of Offers sent in that same time period.  If they are zero, we know there is likely a problem with communication.  

Conclusion:  This is just a suggestion.  No building will topple if this isn't put into place.  However, making the application easier to understand for the user would go a long way to reducing Support requests, as well as reassuring users that they have things setup properly.  

Also, consider that someone who has no knowledge of Storj, and wants to become involved.  They have no history with the product.  They don't understand how shard distribution happens, or whether their nodes are preferred, have a reputation problem, are too slow, or that Storj is giving shards to whoever the developers prefer and not to them.  "Is it random?  Am I getting less because my device sucks?"  These individuals do not share our confidence with how the product works.  So this visual reassurance that they are doing everything correctly is a kind of feel good entry way into a greater understanding of what Storj is all about.  It should be made easier for them to join the Storj party.  

Thanks for taking the time to consider this suggestion.

**Comment by MeijeSibbel** [comment] 2017-03-30 20:50
I 100% agree with this. It is absolutely essential that we strive towards doing all the heavy lifting and issue/error catching for the user and remove any form of farmer doubt. The logs in combination with the API's give a wealth of information about the status of one's node, from database corruption to incorrect time synchronization to incorrect user configuration to closed ports. All of this data is already there, the logs are stored on the user's computer, the API's are free to access and port checker code clocks are available everywhere. Adding some monitor routines to the GUI should not be too much work for the brilliant developers at Storj.

My personal suggestion would be to add the following information fields to the GUI from left to right:

1- Use the stop-sign color code idea from knowledge.
2-  Add a contract counter
3- Add a last activity filed
4- Add a field that illustrates through which port storjshare is connected and which protocol it is using (UPnP or TCP, or tunnel connection), e.g. `4000 (TCP)` , make the text green when the port checker returns that the port is actually open, set both (1) and the port text to red when the port is closed and stop the node.
5- To the right of this add a error catcher fields which returns a short text string when a critical error occurs (e.g. ERROR: Database corruption). Database corruption errors are actually the only real critical errors that occur in the logs, all other issues are not critical and are just due to node configuration or connection issues and thus can be handled with simple status info explained in the previous points.
6- Next to this the delta value should be displayed (as long as NTP sync is still mandatory), where the text will change color from red to green, if red, a message is returned to the users and the node will not start until the issue is fixed (of course the necessary solution links are included)

To take this even a step further, the logs do not only show relevant error messages and information regarding the status of the node, they are also a perfect source for statistical information which can be utilized to make all sorts of graphical plots. For example below each node a offer plot can be illustrated (y-axis = time, x-axis = offers) which will clearly tell the user that not only data supply is not linear (which is very confusing for new users) but also when data supply has been maximum, when minimum... All very useful information which is all contained within the logs. @realshels on Rocketchat actually already build a program that does all this, it even catches all sorts of errors and checks the ports, response times with the API's..., if he can build this, why shouldn't we add it this very useful info to the GUI?.

Having things that move psychologically tells the user that StorjShare is working, we should strive towards adding a few moving elements to the GUI like graphs and status bars, this will give the farmers piece of mind. 

Currently as Knowledge already stated one of the largest issues is that farmers are running nodes which appear to be working from the front-end app but are actually not running at all due to severe database corruption. I have seen farmers running such nodes for literally months before getting in contract with us to solve the issue, this CANNOT continue like this anymore, either the nodes work or they don't , you can't be half pregnant. The new GUI should Stop the node automatically if any error occurs that prevents correct node functioning and should not start anymore as long as these issues are resolved, this will force the user to automatically search for help. Implementing this will greatly increase the reliability of the farming node on the network because only fully functional nodes are connected. Right now these nodes still talk to the bridge (and thus use the bridge's resources) but are never able to participate in the network, a complete waste of resources on both sides.

I understand that farmers only cost money and that for Storj to survive we need renters, however, it is my opinion that making a good GUI will solve allot of the stability issues we are now seeing and will give Storj much more confidence to attract new companies to use the storj service.

**Comment by MeijeSibbel** [comment] 2017-04-01 23:35
Bellow are a few rough sketches that graphically demonstrate our ideas above:

![port forwarding](https://cloud.githubusercontent.com/assets/11735738/24583250/fa983632-173b-11e7-9f16-13177c60f9dc.png)
![port_closed](https://cloud.githubusercontent.com/assets/11735738/24583252/015d8f12-173c-11e7-8453-b02ee3588958.png)
![tunnels](https://cloud.githubusercontent.com/assets/11735738/24583254/0a1c3b80-173c-11e7-8a2e-72d87d9d492f.png)
![failed to connect](https://cloud.githubusercontent.com/assets/11735738/24583258/19dd877c-173c-11e7-9b52-ba0eb7d99064.png)
![graph](https://cloud.githubusercontent.com/assets/11735738/24583259/23044a66-173c-11e7-804a-801990256171.png)

**Comment by MeijeSibbel** [comment] 2017-04-02 11:52
What would also be very helpful is add a payout counter using for example the script from @littleskunk  https://gist.github.com/littleskunk/e91148b62263d49bc9e2c9501169392b and inputs the results into this formula https://gist.github.com/littleskunk/e91148b62263d49bc9e2c9501169392b , the results are then added to the counter say once a day. The issue with this though is that i see the payout formula from @super3 is still dependent on mean values and standard deviation of the total network. I find this kinda strange though as we are already out of Beta and renters are paying for Storage at a fixed price and so the payout is not just the fixed 12k USD/month for all farmers. The other thing is that this script takes some time (and resources) for calculation. However i think a estimation/hybrid calculation would be possible.

**Comment by MeijeSibbel** [comment] 2017-04-03 22:50
As the bridge also tracks the payable GB/h for each node-ID it would be relatively easy to create a public API where the input string is the node-ID and the output is the estimated payout value in USD or SJCX. The only thing the API service has to do is input the GB/h value for that specific node-ID into the payout formula, which then prints out a SJCX or USD value which the API will return.
The GUI can then pull that information from the public API and display it as a within a status filed. Updating the parameter every 6 hours or so would be more than enough.

**Comment by nerdatwork** [comment] 2017-05-03 15:34
Currently released version 5 is not user friendly.
1. Payout address is not shown
2. Total balance not shown
3. Whether I am getting offers or not is not shown.
4. How much space I have offered for a node is not shown.
5. If someone accidentally clicks delete for a node there is no going back. A prompt must be given to double check if user really wants to delete the node. 

Enhancements:
1. Title bar should show version info next to Storj Share in GUI like **Storj Share ver. 4.1.1** 
2. If a new update is available this could be shown in title or a marquee text in the GUI notifying user that a new version is available and an approximate timeline till user is **forced to update**.

**Comment by RichardLitt** [comment] 2018-10-30 12:40
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!

**Closed by RichardLitt** 2018-10-30 12:40 UTC
Labels: design, enhancement, ux
