### ISSUE TITLE
storageAllocation not set

### ISSUE THREAD

**Issue by osok** [storj/storjshare-gui#572] opened 2017-05-07 18:58 UTC
### Versions

Replace the values below with your own:

- **GUI Version:** Linux Gui v5.0.1
- **Operating System:** Ubuntu 14.04 LTS

### Expected Behavior

Please describe the program's expected behavior.
I run the wizard enter all the values including the size 1TB and the configuration file should eflect 1TB

```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

I just looked at my configuration and it tells me "storageAllocation": 0, I know I told the wizard 1 TB

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...Run Linux GUI
2. ...Go through Wizard
3. ...Enter storage allocation
4 Edit configuration  (notice the 0 in storageAllocation)

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by MrFancyMonocle** [comment] 2017-05-15 15:10
Unable to reproduce the bug on Ubuntu 16.04 LTS machine. Is this occurring consistently for you? If you add another drive, does this occur again, or was it only seen once or infrequently.

**Comment by RichardLitt** [comment] 2018-10-30 12:40
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!

**Closed by RichardLitt** 2018-10-30 12:40 UTC
Labels: more info needed
